fixed the deployment

diff --git a/.github/workflows/hugo.yaml b/.github/workflows/hugo.yaml
--- a/.github/workflows/hugo.yaml
+++ b/.github/workflows/hugo.yaml
@@ -20,7 +20,6 @@ env:
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -37,12 +36,12 @@ jobs:
       - name: Build Hugo site
         run: hugo -s web --destination ./public -D
 
-    - name: Debug: list contents
-      run: |
-        echo "Root directory:"
-        ls -alh
-        echo "Public directory:"
-        ls -alh ./public || echo "❌ ./public not found"
+      - name: Debug: list contents
+        run: |
+          echo "Root directory:"
+          ls -alh
+          echo "Public directory:"
+          ls -alh ./public || echo "❌ ./public not found"
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
